### ISSUE TITLE
Authenticated users security

### ISSUE THREAD

**Issue by CPowell23** [lucyconklin/little_shop#48]
issueThirteen:

    body: >
      Background: An authenticated user 
      As an Authenticated User
      I cannot view another user's private data (current or past orders, etc)
      I cannot view the administrator screens or use admin functionality
      I cannot make myself an admin

**Comment by lucyconklin** [comment]
I cannot view the administrator screens or use admin functionality - can you see if we already tested for this?
 ( I cannot make myself an admin) This one doesn't really apply to us, ok to ignore
